version: '3'

services:
  cron_sidecar:
    build:
      context: cron-docker/
    image: 'joomla-cron:latest'

  restore_sidecar:
    build:
      context: joomla/
    image: 'joomla-restore:latest'
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: us-east-2
      S3_BUCKET_NAME: scos-prod-joomla-backups
      S3_FILE_NAME: site-www.smartcolumbusos.com-20180628-200001edt.zip
      JOOMLA_SITE_NAME: Smart Columbus Operating System
      JOOMLA_ADMIN_EMAIL: foo@example.com
      JOOMLA_SITE_URL: http://${NGINX_HOST}
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: foobarpass1
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_PREFIX: smrt_
    volumes:
      - joomla-data:/var/www/html

  joomla:
    image: 'joomla:3.8.8-php5.6-apache'
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: foobarpass1
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_PREFIX: smrt_
    volumes:
      - joomla-data:/var/www/html

  nginx:
    build:
      context: nginx/
    image: joomla-nginx:latest
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_HOST: ${NGINX_HOST}

  joomladb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: foobarpass1

volumes:
  joomla-data:
